autosnap/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('indexapp.urls')),
]

indexapp/urls.py
from django.urls import path
from . import views

app_name = 'indexapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('list', views.PageListView.as_view(), name='list'),
    path('<int:page_id>/', views.detail, name='detail')
]

indexapp/models.py
from django.db import models


class ImagePost(models.Model):
    image_path = models.TextField(max_length=65535)
    page_title = models.CharField(max_length=200)
    url = models.TextField(max_length=65535, null=False, default="")
    url_hash = models.CharField(max_length=128, null=True)
    page_content = models.TextField(null=True)
    gmt_create = models.DateTimeField(auto_now_add=True)
    gmt_modify = models.DateTimeField(auto_now=True)

indexapp/forms.py
from django import forms


class PostUrlForm(forms.Form):
    url = forms.CharField(required=True)

indexapp/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse
from .models import ImagePost
from .forms import PostUrlForm
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
import os
import time
from django.core.files import File
from autosnap import settings
import datetime
import hashlib
import pathlib
from django.views import generic
from django.core.exceptions import ObjectDoesNotExist


# Create your views here.

def get_image(url, pic_path):
    # chromedriver的路径
    chromedriver = settings.CHROME_DRIVE
    os.environ["webdriver.chrome.driver"] = chromedriver
    # 设置chrome开启的模式，headless就是无界面模式
    # 一定要使用这个模式，不然截不了全页面，只能截到你电脑的高度
    chrome_options = Options()
    chrome_options.add_argument('headless')
    driver = webdriver.Chrome(chromedriver, chrome_options=chrome_options)
    # 控制浏览器写入并转到链接
    driver.get(url)
    time.sleep(1)
    # 接下来是全屏的关键，用js获取页面的宽高，如果有其他需要用js的部分也可以用这个方法
    width = driver.execute_script("return document.documentElement.scrollWidth")
    height = driver.execute_script("return document.documentElement.scrollHeight")
    title = driver.execute_script("return document.title")
    filename = hashlib.md5(url.encode(encoding='UTF-8')).hexdigest()+".png"
    # 将浏览器的宽高设置成刚刚获取的宽高
    driver.set_window_size(width, height)
    time.sleep(1)
    # 截图并关掉浏览器
    driver.save_screenshot(os.path.join(pic_path, filename))
    driver.close()
    return title, filename


def index(request):
    if request.method == 'POST':
        posted = False
        form = PostUrlForm(request.POST)
        if form.is_valid():
            url = form.data.get("url")
            url_hash = hashlib.md5(url.encode(encoding='UTF-8')).hexdigest()

            post_count = ImagePost.objects.filter(url_hash=url_hash).count()
            print(post_count)
            if post_count > 0:
                exist_post = ImagePost.objects.get(url_hash=url_hash)
                return HttpResponseRedirect(reverse('indexapp:detail', args=(exist_post.id,)))

            now = datetime.datetime.now()
            relative_path = os.path.join('snapshot', str(now.year), str(now.month), str(now.day))
            image_path = os.path.join(settings.MEDIA_ROOT, relative_path)
            pathlib.Path(image_path).mkdir(parents=True, exist_ok=True)

            img_info = get_image(url, image_path)
            post = ImagePost(page_title=img_info[0],
                             image_path=os.path.join(relative_path, img_info[1]),
                             url=url,
                             url_hash=url_hash)
            post.save()
            return HttpResponseRedirect(reverse('indexapp:detail', args=(post.id,)))

    else:
        form = PostUrlForm(initial={})
        posted = True

    return render(request, 'index.html', {'form': form, 'posted': posted})


def detail(request, page_id):
    page = get_object_or_404(ImagePost, pk=page_id)
    return render(request, 'detail.html', {'page': page})


class PageListView(generic.ListView):
    template_name = 'list.html'
    context_object_name = 'page_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return ImagePost.objects.all()

indexapp/templates/detail.html
{%  extends 'layout.html' %}
{% load static %}
{% block content %}

<div>
    <h1>{{ page.page_title }}</h1>
    <p>
        url: <a href="{{page.url}}">{{page.url}}</a>
    </p>
    <p>
        url_hash: {{page.url_hash}}
    </p>
    <p>
        <img src="{% static page.image_path %}" alt="" />
    </p>
</div>

{% endblock %}

indexapp/templates/index.html
{%  extends 'layout.html' %}
{% block content %}
<div style="margin-top: 10px;">
    <form method="post" action="{% url 'indexapp:index' %}">
        {% csrf_token %}
        <div class="form-group">
            <input type="text" class="form-control" id="webUrl" placeholder="请将浏览器的url粘贴到此处" name="url">
            {% if form.url.errors and posted %}
            <span id="url-error-msg" class="help-block">
        {% for error in form.url.errors %}
            {{ error|escape }}
        {% endfor %}
        </span>
            {% endif %}
        </div>
        {{ form.non_field_errors }}
        <div class="d-flex justify-content-center">
          <button type="submit" class="btn btn-primary">提交</button>
        </div>

    </form>
</div>

{% endblock %}

indexapp/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Title</title>
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="{% static 'bootstrap-4.4.1-dist/css/bootstrap.min.css' %}" crossorigin="anonymous">
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'indexapp:index' %}">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item {% if request.resolver_match.url_name == 'index' %}active{%endif%}">
                    <a class="nav-link" href="{% url 'indexapp:index' %}">首页
                        {% if request.resolver_match.url_name == 'index' %}
                        <span class="sr-only">(current)</span>
                        {% endif %}
                    </a>
                </li>
                <li class="nav-item {% if request.resolver_match.url_name == 'list' %}active{%endif%}">
                    <a class="nav-link" href="{% url 'indexapp:list' %}">列表页
                        {% if request.resolver_match.url_name == 'list' %}
                        <span class="sr-only">(current)</span>
                        {% endif %}
                    </a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
<div class="container">
    {% block content %}

    {% endblock %}
</div>
<script src="{% static 'bootstrap-4.4.1-dist/js/jquery.min.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'bootstrap-4.4.1-dist/js/popper.min.js' %}" crossorigin="anonymous"></script>
<script src="{% static 'bootstrap-4.4.1-dist/js/bootstrap.min.js' %}" crossorigin="anonymous"></script>
</body>
</html>

indexapp/templates/list.html
{%  extends 'layout.html' %}
{% block content %}
<ul>
    {% for page in page_list %}
    <li><a href="{% url 'indexapp:detail' page.id %}">{{ page.page_title | escape }} - {{ page.gmt_create }}</a></li>
    {% endfor %}
</ul>

{% endblock %}